/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kevoree_microsandbox_javase_components_InterprocessLock */

#ifndef _Included_org_kevoree_microsandbox_javase_components_InterprocessLock
#define _Included_org_kevoree_microsandbox_javase_components_InterprocessLock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kevoree_microsandbox_javase_components_InterprocessLock
 * Method:    waitInterprocess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ipc_memory_InterprocessLock_waitInterprocess
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_kevoree_microsandbox_javase_components_InterprocessLock
 * Method:    broadcast
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ipc_memory_InterprocessLock_broadcast
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_kevoree_microsandbox_javase_components_InterprocessLock
 * Method:    waitInterprocess2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ipc_memory_InterprocessLock_waitInterprocess2
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_kevoree_microsandbox_javase_components_InterprocessLock
 * Method:    broadcast2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ipc_memory_InterprocessLock_broadcast2
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_kevoree_microsandbox_javase_components_InterprocessLock
 * Method:    lock
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ipc_memory_InterprocessLock_lock
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_kevoree_microsandbox_javase_components_InterprocessLock
 * Method:    unlock
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ipc_memory_InterprocessLock_unlock
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_kevoree_microsandbox_javase_components_InterprocessLock
 * Method:    createNew
 * Signature: ([BZ)I
 */
JNIEXPORT jint JNICALL Java_org_ipc_memory_InterprocessLock_createNew
  (JNIEnv *, jclass, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
