/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kevoree_microsandbox_javase_CPUThreadControl */

#ifndef _Included_org_kevoree_microsandbox_javase_CPUThreadControl
#define _Included_org_kevoree_microsandbox_javase_CPUThreadControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kevoree_microsandbox_javase_CPUThreadControl
 * Method:    assignLimit
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kevoree_microsandbox_cgroupNode_CPUThreadControl_assignLimit
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_kevoree_microsandbox_javase_CPUThreadControl
 * Method:    attach
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kevoree_microsandbox_cgroupNode_CPUThreadControl_attach
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_kevoree_microsandbox_javase_CPUThreadControl
 * Method:    setFrozen
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kevoree_microsandbox_cgroupNode_CPUThreadControl_setFrozen
  (JNIEnv *, jclass, jint, jboolean);

JNIEXPORT jint JNICALL Java_org_kevoree_microsandbox_cgroupNode_CPUThreadControl_getTTID
(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
